### ISSUE TITLE
[Editor] Layer names containing & don't work

### ISSUE THREAD

**Issue by enjlectric** [WohlSoft/Moondust-Project#564] opened 2023-04-24 15:04 UTC
![image](https://user-images.githubusercontent.com/125742366/234034947-5775d3d0-859a-44b1-b806-dbc1bb2ef07b.png)
![image](https://user-images.githubusercontent.com/125742366/234035028-70c1f10d-4c17-4fc0-a6f0-7eb3700bec7d.png)
![image](https://user-images.githubusercontent.com/125742366/234034883-47fbca8e-c561-447a-acfa-38e1521418ef.png)
![image](https://user-images.githubusercontent.com/125742366/234035102-a5adad3c-0afe-43a7-a321-b3d0021a1f64.png)
![image](https://user-images.githubusercontent.com/125742366/234035148-e06ec8d1-5fa6-42e6-8fa2-904e63aca5b3.png)
![image](https://user-images.githubusercontent.com/125742366/234035215-dd146805-0695-49d3-8466-a50ce8a19bf4.png)
![image](https://user-images.githubusercontent.com/125742366/234035260-2c11cea8-a548-437e-b5fd-d89ffc7a8123.png)
![image](https://user-images.githubusercontent.com/125742366/234035296-dde437a9-cac6-4463-9ed4-38e070574ddd.png)
![image](https://user-images.githubusercontent.com/125742366/234035562-447cd9c0-101d-4d1d-b408-cf8b2967fefe.png)

There may be more symbols that exponentially multiply whenever the context menu is opened.

![image](https://user-images.githubusercontent.com/125742366/234037260-02dda6a3-65ff-439b-ab47-197739b13d24.png)

**Comment by Wohlstand** [comment] 2023-04-24 16:22
I had to add a workaround to some of cases like this, but here, seems, I hadn't paid attention. I'll fix this as fast as possible. Thanks for the catch!

**Comment by Wohlstand** [comment] 2023-04-24 22:35
Das ist scheiße!
![изображение](https://user-images.githubusercontent.com/6751442/234130943-a9bd0597-2721-4a14-a4b4-9337581de8b8.png)

It supposed to return the replaced content without overriding the string itself, but it actually breaks the line... Gonna fix this...

**Comment by Wohlstand** [comment] 2023-04-24 22:48
Fixed just now:

https://user-images.githubusercontent.com/6751442/234132589-073fc86a-5fb7-48c2-9777-72b8f2a618d2.mp4

**Comment by Wohlstand** [comment] 2023-04-24 22:49
@enjlectric, I fixed the thing, so, the working build will appear somewhere after 30 minutes on CI. Feel free to test out the thing.

**Comment by SkullGamer205** [comment] 2023-04-24 23:04
👀

**Comment by Wohlstand** [comment] 2023-05-17 01:01
@enjlectric, ping?

**Comment by Emral** [comment] 2023-05-17 08:41
Sorry I thought "feel free to test it out" meant testing it months later or not testing it at all would be fine as well because you had already confirmed it.

Seems to work, thanks.

**Comment by Wohlstand** [comment] 2023-05-17 10:56
There is a workflow algorithm, and the user-end testing is required to ensure nothing broken or missing. That sometimes happens, and after that, b need to fix the messed stuff. Anyway, thanks for explaining the case of a bad parade choice:)

I'll close this now as you confirmed it works.

**Closed** 2023-05-17 10:56 UTC
Labels: bug
